### ISSUE TITLE
negating the offsets

### ISSUE THREAD

**Issue by danpovey** [waldo-seg/waldo#47]
Guys, this is what I mentioned on the list last night.
I think this is the reason Yiwen is not getting perfect results with the oracle masks.
On this line, you need to negate the offsets.    If you want the current pixel to contain the reference at this pixel plus the offset, you need to roll the image with the *negative* of the offset.

https://github.com/waldo-seg/waldo/blob/3566eaec5752796eb569e32d2f95b9e5effe8165/scripts/waldo/data_manipulation.py#L160

**Comment by YiwenShaoStephen** [comment]
Got it. I will fix it.
