### ISSUE TITLE
swap height, width

### ISSUE THREAD

**Issue by danpovey** [waldo-seg/waldo#50]
https://github.com/waldo-seg/waldo/blob/540c3cbe1488e487c2c00a72240d95aaf9e65c4d/scripts/waldo/segmenter.py#L233

I think after we created the code we changed the indexing conventions.
this may be a purely cosmetic change.

**Comment by danpovey** [comment]
also see line 263, they seem swapped there too.

**Comment by hhadian** [comment]
Fixed in #57
